trigger:
  - main
  - feature/*

pr:
- main
- releases/*

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      ref: pl-5-ado-sonar
      
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters: 
    appFrameworkType: nodejs
    

    