name: 3.$(Rev:r)

trigger:
  - main
  - feature/*

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      ref: feature/stage-init

extends:
  template: fcp-common-pipeline.yaml@templates

