services:
  ffc-demo-apply-web:
    command: npm run start:watch
    build:
      target: development
    image: ffc-demo-apply-web-development
    environment:
      NODE_ENV: test
      APPLY_QUEUE_ADDRESS: ${APPLY_QUEUE_ADDRESS:-ffc-demo-claim}
    volumes:
      - ./test-output:/home/node/test-output

  zap-baseline-scan:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl ${TEST_ENVIRONMENT_ROOT_URL:-http://ffc-demo-apply-web:3000} -zapit ${TEST_ENVIRONMENT_ROOT_URL:-http://ffc-demo-apply-web:3000} -configfile config/zap.conf -quickout test-output/zap-report.html -silent -quickprogress
    depends_on:
      - ffc-demo-apply-web
    volumes:
      - ./test-output:/zap/test-output
      - ./zap:/zap/config
