services:
  ffc-demo-apply-web:
    build:
      context: .
      target: development
    image: ffc-demo-apply-web-development
    container_name: ffc-demo-apply-web
    command: npm run test
    environment:
      NODE_ENV: test
      PACT_BROKER_URL: ${PACT_BROKER_URL}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD}
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
