services:
  ffc-demo-apply-web:
    build:
      context: .
      target: production
    image: ffc-demo-apply-web
    container_name: ffc-demo-apply-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-apply-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      APPLY_QUEUE_ADDRESS: ${APPLY_QUEUE_ADDRESS:-ffc-demo-apply}${MESSAGE_QUEUE_SUFFIX}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PROTECTIVE_MONITORING_URL: ${PROTECTIVE_MONITORING_URL}
      REDIS_HOSTNAME: redis
      GOOGLE_TAG_MANAGER_KEY: GTM-N5QK7RL
