environment: development
environmentCode:
name: ffc-demo-apply-web
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-apply-web

appInsights:
  connectionString:

labels:
  component: web

containerConfigMap:
  name: ffc-demo-apply-web-config-map

containerSecret:
  name: ffc-demo-apply-web-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:
  useLinkerd: true

service:
  port: 80
  type: ClusterIP

container:
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-demo
  imagePullPolicy: Always
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 80Mi
  limitCpu: 80m
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
  port: 3000
  cookiePassword: passwordpasswordpasswordpasswordpassword
  messageQueueHost: amq
  applyQueueAddress: ffc-demo-apply
  googleTagManagerKey: GTM-N5QK7RL
  protectiveMonitoringUrl:

ingress:
  class: nginx
  endpoint: ffc-demo-apply-web
  server: example.com

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID