---
environment: production
environmentCode: prd
secretProviderClass.azure.keyvaultName: PRDFFCINFKV1001
container.applyQueueAddress: ffc-demo-apply
container.protectiveMonitoringUrl: https://prod-52.northeurope.logic.azure.com:443/workflows/7b54bcdf13134cfbb63edd95d7fb81f2/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=kVFdY0yXQ08l81Y9E2tlsBviD1FriETI1DlznFfhKCI
container.redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
container.messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
ingress.server: azure.defra.cloud
ingress.endpoint: ffc-demo-prd