{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-apply-web.container-secret") -}}
{{- define "ffc-demo-apply-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
